# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            pattern: ^/
            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
              # https://symfony.com/doc/3.4/security/csrf_in_login_form.html
              csrf_token_generator: security.csrf.token_manager

            # https://symfony.com/doc/3.4/security/remember_me.html
            remember_me:
              secret: '%secret%'
              lifetime: 604800 # 1 week in seconds

            anonymous: true
            logout: true

            logout_on_user_change: true

            # !!! worked only for non-anonymous users
            access_denied_url: /login

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout$, role: ROLE_USER }
        - { path: ^/, role: ROLE_USER }
